/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tools.mahmoudmabrok.imagehelper;

import java.util.logging.Level;
import java.util.logging.Logger;
import tools.mahmoudmabrok.imagehelper.logic.ImagesController;

/**
 *
 * @author mo3tamed
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfPath = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        lbStatus = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tfW = new javax.swing.JFormattedTextField();
        tfH = new javax.swing.JFormattedTextField();
        btnRenamePrefix = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        tfPrefix = new javax.swing.JTextField();
        btnChangrToWH1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(28, 47, 47));
        setForeground(new java.awt.Color(243, 233, 233));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(240, 240, 242));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 9, 65));
        jLabel1.setText("Image Helper");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 12, -1, -1));

        tfPath.setText("/home/mo3tamed/Videos/images/");
        tfPath.setToolTipText("path to images directory ");
        tfPath.setName("tfDirectory"); // NOI18N
        tfPath.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPathFocusGained(evt);
            }
        });
        tfPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPathActionPerformed(evt);
            }
        });
        add(tfPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 57, 373, -1));

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 115, -1, -1));

        lbStatus.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        lbStatus.setForeground(new java.awt.Color(237, 235, 235));
        lbStatus.setText("NA");
        add(lbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 455, -1));

        jLabel3.setForeground(new java.awt.Color(244, 236, 236));
        jLabel3.setText("Status:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel2.setForeground(new java.awt.Color(235, 228, 228));
        jLabel2.setText("Change images to be fitted with Google Play rules");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 115, 404, 30));

        jLabel4.setForeground(new java.awt.Color(241, 234, 234));
        jLabel4.setText("Rename all files with prefix            ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 240, 24));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 157, 465, -1));
        add(tfW, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 182, 49, -1));
        add(tfH, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 182, 49, -1));

        btnRenamePrefix.setText("Start");
        btnRenamePrefix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenamePrefixActionPerformed(evt);
            }
        });
        add(btnRenamePrefix, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        jLabel5.setForeground(new java.awt.Color(237, 235, 235));
        jLabel5.setText("Path::");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 62, 77, -1));

        jSeparator2.setBackground(java.awt.Color.white);
        jSeparator2.setForeground(new java.awt.Color(241, 227, 227));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 480, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 465, 10));

        jLabel6.setForeground(new java.awt.Color(241, 234, 234));
        jLabel6.setText("Change Width, Height to ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 184, 187, 24));

        tfPrefix.setText("a");
        add(tfPrefix, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 120, -1));

        btnChangrToWH1.setText("Start");
        btnChangrToWH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangrToWH1ActionPerformed(evt);
            }
        });
        add(btnChangrToWH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 181, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tfPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPathActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        String path = tfPath.getText();
        if (path != null) {
            showMessage("Starting.....");
        } else {
            showMessage("Invalid Path");
        }

    }//GEN-LAST:event_btnStartActionPerformed

    private void tfPathFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPathFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_tfPathFocusGained

    private void btnRenamePrefixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenamePrefixActionPerformed
        // TODO add your handling code here:
        showMessage("Starting....");
        try {
            Thread.sleep(1500);
        } catch (InterruptedException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        String path = tfPath.getText();
        String prefix = tfPrefix.getText();
        String res = ImagesController.renameAll(path, prefix);
        showMessage(res);
    }//GEN-LAST:event_btnRenamePrefixActionPerformed

    private void btnChangrToWH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangrToWH1ActionPerformed
        // TODO add your handling code here:
        showMessage("Starting");
        String path = tfPath.getText();
        int w = Integer.parseInt(tfW.getText());
        int h = Integer.parseInt(tfH.getText());
        String res = ImagesController.resize(path, w,h);
        showMessage(res);
    }//GEN-LAST:event_btnChangrToWH1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangrToWH1;
    private javax.swing.JButton btnRenamePrefix;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JFormattedTextField tfH;
    private javax.swing.JTextField tfPath;
    private javax.swing.JTextField tfPrefix;
    private javax.swing.JFormattedTextField tfW;
    // End of variables declaration//GEN-END:variables

    private void showMessage(String msg) {
        lbStatus.setText(msg);
    }
}
