/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tools.mahmoudmabrok.imagehelper;

/**
 *
 * @author mo3tamed
 */
public class Start extends javax.swing.JPanel {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(32, 23, 14));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 400, -1));

        jLabel3.setForeground(new java.awt.Color(244, 236, 236));
        jLabel3.setText("Status:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, 30));

        lbStatus.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        lbStatus.setForeground(new java.awt.Color(237, 235, 235));
        lbStatus.setText("NA");
        add(lbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 400, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbStatus;
    // End of variables declaration//GEN-END:variables
}
